### PR TITLE
resolve #58 return error response

### LINKED ISSUE #58: Display the actual error/stack trace in Groovy/Painless script in UI while creation of triggers in Extraction query based alerts.
While creating  a trigger, if there is a error in the painless/groovy script, only a error flag is shown "runtime error", the actual error/stack trace is not displayed, it would greatly improve the user experience if he can see the actual error when he runs the trigger while creating it.

### PR DESCRIPTION
**Pull request by seraphjiang**
This is required api change to support quick fix for #58
There is another long term error exception handle enhancement in my plan. That cause more change is not part of this fix.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt [hunk 1]
```diff
@@ -77,6 +77,10 @@ data class TriggerRunResult(
     val actionResults: MutableMap<String, ActionRunResult> = mutableMapOf()
 ) : ToXContent {
     override fun toXContent(builder: XContentBuilder, params: ToXContent.Params): XContentBuilder {
+        var msg = error?.message;
```
Comment (qreshi) [inline alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: I believe we never use this in the ```XContentBuilder``` after assignment

Comment (seraphjiang) [reply alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: Right.
missed online during copy paste from my working repo to repo for PR.
my bad.

File: alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt [hunk 2]
```diff
@@ -77,10 +77,14 @@ data class TriggerRunResult(
...
+        if(error is ScriptException){
```
Comment (seraphjiang) [inline alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: tested, this is null safe

Comment (ylwu-amzn) [reply alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: Can you post the local build result?

Comment (seraphjiang) [reply alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: actual it failed the build because the code style check, re-formatted code and pass the build, thanks for tips

Comment (seraphjiang) [reply alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: > Can you post the local build result?

actual it failed the build because the code style check, re-formatted code and pass the build, thanks for tips

**Comment by seraphjiang** [comment]
./gradlew :alerting:build

> Configure project :alerting
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.2.1
  OS Info               : Mac OS X 10.13.6 (x86_64)
  JDK Version           : 12 (Oracle Corporation 12.0.1 [Java HotSpot(TM) 64-Bit Server VM 12.0.1+12])
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/Home
  Random Testing Seed   : 14B11DF1003C6EB4
=======================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 1s
40 actionable tasks: 20 executed, 20 up-to-date

File: alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt [hunk 3]
```diff
@@ -25,12 +25,12 @@ import org.elasticsearch.script.ScriptException
 import java.time.Instant
 
 data class MonitorRunResult(
-    val monitorName: String,
-    val periodStart: Instant,
-    val periodEnd: Instant,
-    val error: Exception? = null,
-    val inputResults: InputRunResults = InputRunResults(),
-    val triggerResults: Map<String, TriggerRunResult> = mapOf()
+        val monitorName: String,
```
Comment (qreshi) [inline alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: What message did you get for the code style check? The previous way of using 4 spaces was correct indentation I believe. You can refer to the bottom of the [Class header formatting](https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting) section in Kotlin's documentation.

Comment (seraphjiang) [reply alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: cannot find those anymore, i use use IDEA’s Command + Option + L to format the document, after that all code style error gone.  I could remove space manually, but usually prefer to format code use build-in tool.

Comment (seraphjiang) [reply alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: resolve for now, but feel free to reopen if our team has different practice.

Comment (mihirsoni) [reply alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: @seraphjiang  I feel this change is visible for tab / space, could you verify it is formatting using tabs instead of space.

Comment (seraphjiang) [reply alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: it is space, not tab. IDEA Editor -> code style -> Kotlin (Schema - Default IDE)
Tab Size - 4
Indent - 4
Continuation indent - 8

File: alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt [hunk 4]
```diff
@@ -71,16 +71,20 @@ data class InputRunResults(val results: List<Map<String, Any>> = listOf(), val e
...
-    val error: Exception? = null,
-    val actionResults: MutableMap<String, ActionRunResult> = mutableMapOf()
+        val triggerName: String,
+        val triggered: Boolean,
+        val error: Exception? = null,
+        val actionResults: MutableMap<String, ActionRunResult> = mutableMapOf()
 ) : ToXContent {
     override fun toXContent(builder: XContentBuilder, params: ToXContent.Params): XContentBuilder {
+        var msg = error?.message
+        if (error is ScriptException) {
```
Comment (mihirsoni) [inline alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: You can simplify with kotlin way.
```kt
var max = a 
if (a < b) max = b
```

Comment (seraphjiang) [reply alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: good to learn

File: alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt (hunk 3 above)
Comment (seraphjiang) [reply alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/MonitorRunResult.kt]: @mihirsoni @qreshi 
after a little experiment, here is result
with default ide editor code style settings, we will have to format the class header manually. anyone know better trick, let me know :)
